no-greeting
no-autostart
default-key 07EEE1676D88BFEB3DBC24F7172E752D0D9E700C
charset utf-8
group self = jhujhiti@adjectivism.org
use-agent
personal-digest-preferences SHA256
cert-digest-algo SHA256
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
